name: apollineflutter
description: Apolline sensors app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.2+20
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ^2.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.3.1
  fluttertoast: ^8.0.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  syncfusion_flutter_gauges: ^20.3.48
  get_it: ^7.1.3
  google_maps_flutter: ^2.0.6
  flutter_launcher_icons: ^0.9.0
  http: ^0.13.3
  global_configuration: ^2.0.0-nullsafety.1
  # hash localisation
  geohash: ^0.2.1
  path_provider: ^2.0.2
  # location
  geolocator: ^9.0.2
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.6
  flutter_background: ^1.0.2+1
  easy_localization: ^3.0.0
  grant_and_activate: ^0.0.7
  flutter_local_notifications: ^8.2.0
  flutter_speed_dial: ^4.3.0
  syncfusion_flutter_charts: ^20.3.48
  flutter_picker: ^2.0.2
  qr_code_scanner: ^1.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/config_dev.json
    - assets/translations/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
